nao:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controllers ------------------------------------------------
  HeadYaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: HeadYaw
    pid: {p: 200.0, i: 0.01, d: 10.0}


  HeadPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: HeadPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LShoulderPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: LShoulderPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LElbowYaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: LElbowYaw
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LWristYaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: LWristYaw
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LHand_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHand
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LShoulderRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: LShoulderRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LElbowRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: LElbowRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RShoulderPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: RShoulderPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RElbowYaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: RElbowYaw
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RWristYaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: RWristYaw
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RHand_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHand
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RShoulderRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: RShoulderRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RElbowRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: RElbowRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LHipYawPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHipYawPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LHipRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHipRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LHipPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHipPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LKneePitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: LKneePitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LAnklePitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: LAnklePitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  LAnkleRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: LAnkleRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RHipYawPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHipYawPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RHipRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHipRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RHipPitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHipPitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RKneePitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: RKneePitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RAnklePitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: RAnklePitch
    pid: {p: 200.0, i: 0.01, d: 10.0}


  RAnkleRoll_position_controller:
    type: effort_controllers/JointPositionController
    joint: RAnkleRoll
    pid: {p: 200.0, i: 0.01, d: 10.0}

